name: Relese
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and test
    uses: ./.github/workflows/build-and-test.yml
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download jars
        uses: actions/download-artifact@v3
        with:
          name: user
      - name: Build the Docker image
        run: docker build . --file user/Dockerfile --tag $GITHUB_REF_NAME:$(date +%s)


